site_name: JACoW - Running a FEL Conference
#site_url: https://docs-FEL.JACoW.org
theme: material
repo_name: 'jacow-org/docs-FEL'
repo_url: 'https://github.com/jacow-org/docs-FEL'
nav:
  - Introduction: index.md
  - Glossary: glossary.md 
  - Organising Committees: committees.md
  - Delivery and Initial Setup - Admin:
    - Access to new event: InitialSetup/intro.md
    - Management area: 
      - Settings, Timetable, Protection: InitialSetup/mgmt_area_01.md
      - Organization: InitialSetup/mgmt_area_02.md
      - Workflows: InitialSetup/mgmt_area_03.md
      - Reports: InitialSetup/mgmt_area_04.md
      - Customization: InitialSetup/mgmt_area_05.md
  - Invited Oral Presentations:
    - Introduction: InvitedOrals/intro.md
    - Scientific Secretariat/Admin: 
      - Intial Setup: InvitedOrals/SSsetup.md
      - How submission will work: InvitedOrals/SSsubmission.md
      - Call for Proposals for Invited Oral Presentations: InvitedOrals/SScall.md
      - Post submission duties: InvitedOrals/SSpostsubmit.md
      - Abstract Initial QA: InvitedOrals/SSinitialQA.md
      - Setups for the SPC review: InvitedOrals/SSSPCsetup.md
      - Creating sessions and assigning programme codes: InvitedOrals/SSpcodes.md
      - Publishing the programme: InvitedOrals/SSpublishing.md
      - Invitation to invited speakers: InvitedOrals/SSinviteinvited.md
#    - SPC/OC/SAB:
#      - Submission of Proposals for Invited Oral Presentations: InvitedOrals/SABsubmission.md
#      - "SPC: proposal of track changes": InvitedOrals/SPCtrackreview.md
#      - "SPC MC Coordinators: review tracks": InvitedOrals/MCCtrackreview.md
#      - "SPC: give priority to proposals": InvitedOrals/SPCprioritization.md
#      - "SPC MC Coordinators: accept proposals": InvitedOrals/MCCaccept.md
  - Contributed Oral Presentations:
    - Introduction: ContributedOrals/intro.md
    - SPC:
      - "SPC: proposal of track changes": ContributedOrals/SPCtrackreview.md
      - "SPC Session Chairs: review tracks": ContributedOrals/MCCtrackreview.md
      - "SPC: give priority to proposals": ContributedOrals/SPCprioritization.md
      - "SPC Session Chairs: accept proposals": ContributedOrals/MCCaccept.md
  - Paper editing:
    - Introduction: PaperEditing/intro.md
    - Editor-in-chief:
      - Setting up: PaperEditing/EIC/setup.md
      - Configuring: PaperEditing/EIC/config.md
      - Editing Team Setup: PaperEditing/EIC/team.md
      - Start Editing: PaperEditing/EIC/open.md
      - Publishing: PaperEditing/EIC/publish.md
    - Editor: 
      - Assigning an editable: PaperEditing/Editor/assign.md
      - Editing an editable: PaperEditing/Editor/edit.md
    - Author: 
      - Submitting a paper: PaperEditing/Author/submit.md
      - Sending comments to editors: PaperEditing/Author/comment.md
      - Uploading new version: PaperEditing/Author/upload.md
      - Approving new version by editor: PaperEditing/Author/approve.md

